### PR TITLE
Only set low/high temps on transition out of safe

### PR DESCRIPTION
**Pull request by BobVul**
Setting them every iteration invalidates any checks below that point. Only set them once, when transitioning out of the safe zone.

### CODE REVIEW

**Comment by AlexVerrico** [comment]
G'Day @BobVul 
What version(s) of Python and Octoprint have you tested this with? (And also, which 3D Printer models ideally)
Cheers, Alex.

**Comment by BobVul** [comment]
This was tested against Python 3.7.3 / Octoprint 1.7.0 / Wanhao Duplicator i3

Notably, as I described in https://github.com/AlexVerrico/Octoprint-ThermalRunaway/issues/27#issuecomment-955144423, the existing logic does not appear to work in any situation. With >= V3, it always trips. With < V3, it never trips. Here, I ran a test with 3.0.2 in < V3 mode, where I attached a separate thermistor starting at 50 and let it cool down while commanding the printer to heat - a classic thermistor (or heater) detached failure:

```
2021-11-02 16:57:23,652 - octoprint.plugins.ThermalRunaway - INFO - low = 47.55, high = 58.1, current = 47.55, set = 200.0
2021-11-02 16:57:23,655 - octoprint.plugins.ThermalRunaway - WARNING - thermalLowCount == 1 for T0
2021-11-02 16:57:25,656 - octoprint.plugins.ThermalRunaway - INFO - low = 44.6, high = 58.1, current = 44.6, set = 200.0
2021-11-02 16:57:25,656 - octoprint.plugins.ThermalRunaway - WARNING - thermalLowCount == 1 for T0
2021-11-02 16:57:29,669 - octoprint.plugins.ThermalRunaway - INFO - low = 37.36, high = 58.1, current = 37.36, set = 200.0
2021-11-02 16:57:29,670 - octoprint.plugins.ThermalRunaway - WARNING - thermalLowCount == 1 for T0
2021-11-02 16:57:31,665 - octoprint.plugins.ThermalRunaway - INFO - low = 34.25, high = 58.1, current = 34.25, set = 200.0
2021-11-02 16:57:31,666 - octoprint.plugins.ThermalRunaway - WARNING - thermalLowCount == 1 for T0
2021-11-02 16:57:35,676 - octoprint.plugins.ThermalRunaway - INFO - low = 31.32, high = 58.1, current = 31.32, set = 200.0
2021-11-02 16:57:35,678 - octoprint.plugins.ThermalRunaway - WARNING - thermalLowCount == 1 for T0
2021-11-02 16:57:39,672 - octoprint.plugins.ThermalRunaway - INFO - low = 28.7, high = 58.1, current = 28.7, set = 200.0
2021-11-02 16:57:39,673 - octoprint.plugins.ThermalRunaway - WARNING - thermalLowCount == 1 for T0
2021-11-02 16:57:43,679 - octoprint.plugins.ThermalRunaway - INFO - low = 26.62, high = 58.1, current = 26.62, set = 200.0
2021-11-02 16:57:43,680 - octoprint.plugins.ThermalRunaway - WARNING - thermalLowCount == 1 for T0
2021-11-02 16:57:47,681 - octoprint.plugins.ThermalRunaway - INFO - low = 25.58, high = 58.1, current = 25.58, set = 200.0
2021-11-02 16:57:47,683 - octoprint.plugins.ThermalRunaway - WARNING - thermalLowCount == 1 for T0
2021-11-02 16:57:49,765 - octoprint.plugins.ThermalRunaway - INFO - low = 25.19, high = 58.1, current = 25.19, set = 200.0
2021-11-02 16:57:49,766 - octoprint.plugins.ThermalRunaway - WARNING - thermalLowCount == 1 for T0
```

The info logging code was inserted right after the minTemp/maxTemp setting, where I believe low/high are being incorrectly reset on every cycle. Note that low is always exactly equal to current before it gets to the thermal runaway checks below.

---


This is a re-test with this PR:

```
2021-11-02 17:16:03,849 - octoprint.plugins.ThermalRunaway - INFO - low = 59.71, high = 32.45, current = 59.71, set = 200.0
2021-11-02 17:16:03,853 - octoprint.plugins.ThermalRunaway - WARNING - thermalLowCount == 1 for T0
2021-11-02 17:16:05,863 - octoprint.plugins.ThermalRunaway - INFO - low = 59.71, high = 32.45, current = 59.25, set = 200.0
2021-11-02 17:16:05,864 - octoprint.plugins.ThermalRunaway - WARNING - thermalLowCount == 1 for T0
2021-11-02 17:16:07,857 - octoprint.plugins.ThermalRunaway - INFO - low = 59.71, high = 32.45, current = 53.28, set = 200.0
2021-11-02 17:16:07,857 - octoprint.plugins.ThermalRunaway - WARNING - thermalLowCount == 1 for T0
2021-11-02 17:16:11,863 - octoprint.plugins.ThermalRunaway - INFO - low = 59.71, high = 32.45, current = 46.62, set = 200.0
2021-11-02 17:16:11,864 - octoprint.plugins.ThermalRunaway - WARNING - thermalLowCount > 2 for T0
2021-11-02 17:16:11,870 - octoprint.util.comm - INFO - Force-sending M112 to the printer
```

Note: this PR only works when set to >= V3 logic. With < V3 logic, since the first iteration has low == current, thermalLowCount gets reset to 0 and then bounces between 0 and 1, which triggers the transition from 0 to 1 and the reset of low. With >= V3 logic, the first pass will still trigger an extra cycle up to 2 but it should settle after that first pass as low is now tracking last low properly and not constantly getting reset to current.

I've only tested heating, but cooldown should be symmetrical.

**Comment by BobVul** [comment]
While this is a quick fix to the V3+ logic so it at least works, there's still a few weird spots (like the initial cycle from 0 to 1 to 2 back to 1) that I think should be fixed/avoided, but that would require a considerably more substantial change to the code, almost a rewrite. If you're willing to accept such a change, I can keep going with it and submit a separate PR.

Will probably take a fair bit of time to properly test a more extensive change though. I'll need to properly disconnect my heater cartridge (rather than just detach the thermistor) first so I don't actually start a fire :)

In any case, I'd appreciate it if you could review and hopefully accept this PR first, and maybe remove the pre-V3 workaround option, as I believe that could be actively dangerous to anyone relying on it -- as it currently stands in 3.0.2 I don't believe it could ever trigger. From both my reading of the current code and the tests I've run against it.

**Comment by AlexVerrico** [comment]
I'll try and make time to test this sometime this week, and then merge it.
I have had valid thermal runaways trigger with the current V3+ logic, although thermal runaways are very difficult to practically simulate.

In regards to removing the Pre-V3 logic option, I'll have to run some more tests to confirm that it is definitely broken before removing it, since there was a significant number of users reporting false thermal runaways with the new logic.

I'm definitely open to accepting a PR that rewrites the logic, this plugin was born out of the need to just get something hacked together quickly to get a printer back online.

You may find this plugin useful for testing (it's not in the Plugin Repo though): https://github.com/AlexVerrico/Octoprint-TR_VirtualPrinter
I prefer to still conduct some manual tests (either by replacing the thermistor with a potentiometer, or by removing the heater from the mainboard and connecting it directly to the 12v supply)

(Also, obligatory disclaimer, you shouldn't rely on this plugin no matter what you change about it, it isn't a substitute for firmware based thermal runaway detection and physically monitoring your printer.)

**Comment by BobVul** [comment]
> (Also, obligatory disclaimer, you shouldn't rely on this plugin no matter what you change about it, it isn't a substitute for firmware based thermal runaway detection and physically monitoring your printer.)

Yup, for sure. I meant as an additional line of defense :)

> I prefer to still conduct some manual tests (either by replacing the thermistor with a potentiometer, or by removing the heater from the mainboard and connecting it directly to the 12v supply)

Yes, my current testing was with a separate thermistor and a dehydrator as a heat source, which lets me do a physical simulation of what happens when the thermistor is decoupled from the heater mid-heat. Unfortunately my printer's heater cartridge isn't very easy to disconnect, but I do plan to do so for more extended testing.

> I have had valid thermal runaways trigger with the current V3+ logic

I'm actually quite curious about what conditions would make the V3+ logic work -- on 3.0.2, thermal runaways trigger for me without fail at every heat/cool operation.

---

I've done some further printing/testing with this PR's patch applied, and unfortunately it does not seem to solve the problem entirely - I'm still getting spurious shutdowns. It appears to be an edge case where two adjacent readings have the same temperature value. Odd, as I expect the delay to take care of it.

Sample from a cooldown:

```
2021-11-02 19:21:43,335 - octoprint.plugins.ThermalRunaway - INFO - low = 209.87, high = 165.82, current = 159.38, set = 0.0, heater = T0
2021-11-02 19:21:43,336 - octoprint.plugins.ThermalRunaway - WARNING - thermalHighCount > 2 for T0
2021-11-02 19:21:43,338 - octoprint.plugins.ThermalRunaway - INFO - low = 209.87, high = 165.82, current = 159.38, set = 0.0, heater = T0
2021-11-02 19:21:43,339 - octoprint.plugins.ThermalRunaway - WARNING - thermalHighCount == 1 for T0
2021-11-02 19:21:43,341 - octoprint.plugins.ThermalRunaway - WARNING - thermalHighCount == 1 for T0
2021-11-02 19:21:53,333 - octoprint.plugins.ThermalRunaway - INFO - low = 209.87, high = 159.38, current = 153.67, set = 0.0, heater = T0
2021-11-02 19:21:53,334 - octoprint.plugins.ThermalRunaway - WARNING - thermalHighCount > 2 for T0
2021-11-02 19:21:53,336 - octoprint.plugins.ThermalRunaway - WARNING - thermalHighCount == 1 for T0
2021-11-02 19:21:53,349 - octoprint.plugins.ThermalRunaway - INFO - low = 209.87, high = 153.67, current = 153.67, set = 0.0, heater = T0
2021-11-02 19:21:53,350 - octoprint.plugins.ThermalRunaway - WARNING - thermalHighCount == 1 for T0
2021-11-02 19:21:58,355 - octoprint.plugins.ThermalRunaway - INFO - low = 209.87, high = 153.67, current = 150.73, set = 0.0, heater = T0
2021-11-02 19:21:58,356 - octoprint.plugins.ThermalRunaway - WARNING - thermalHighCount > 2 for T0
2021-11-02 19:21:58,358 - octoprint.plugins.ThermalRunaway - WARNING - thermalHighCount == 1 for T0
2021-11-02 19:22:08,347 - octoprint.plugins.ThermalRunaway - INFO - low = 209.87, high = 150.73, current = 145.42, set = 0.0, heater = T0
2021-11-02 19:22:08,348 - octoprint.plugins.ThermalRunaway - WARNING - thermalHighCount > 2 for T0
2021-11-02 19:22:08,349 - octoprint.plugins.ThermalRunaway - WARNING - thermalHighCount == 1 for T0
2021-11-02 19:22:08,359 - octoprint.plugins.ThermalRunaway - INFO - low = 209.87, high = 145.42, current = 145.42, set = 0.0, heater = T0
2021-11-02 19:22:08,367 - octoprint.plugins.ThermalRunaway - WARNING - thermalHighCount > 2 for T0
2021-11-02 19:22:08,372 - octoprint.util.comm - INFO - Force-sending M112 to the printer
```

Here's what I think is happening:

1. Temperature reading of 159.38 comes in, high (thermalHighCount >=  2 from previous)
2. thermalHighCount >= 2 handler sees current == 159.38 < high == 165.82, sets thermalHighCount = 1 and sets high = current (!!!)
3. In the same loop, thermalHighCount == 1 handler runs and sees high == current, sleeps thread to set thermalHighCount = 2 after a delay
4. Meanwhile, temperatures are still coming in and firing off new threads. thermalHighCount is still == 1, but we're fine since current < high in all these runs. But all these still-running threads are setting high = current to keep high updated. Finally, high = 145.42.
5. The sleeping thread wakes up and sets thermalHighCount = 2
6. Next thread to run will go into the thermalHighCount >= 2 handler, but instead of seeing the high value from the sleeping thread (159.38), it sees the high value from the last thread that ran, 145.42. If we get a double reading *right now*, then it's possible that high == current == 145.42 and this is seen as a runaway.

I think the issues leading up to this are:

* If a thread is sleeping and expecting to transition to level 2, other threads should not be updating high/low for this heater in the meantime. Level 2's temperature should be compared to the one from the sleeping thread.
* Currently, both the level 2 and level 1 handlers run after each other in the one loop iteration. Might be better to only one run (if .. elif).
* Currently, it looks like 2 guarantees the 1 after it in the same loop will transition back into 2, because it sets high/low = current which 1 then checks immediately after. So we're on a <delay> cycle of going 1 ... <delay> ... 2 ... 1 ... <delay> ... 2 etc..

The end result is that while the delay is supposed to prevent a double-reading from triggering a runaway, it doesn't manage to actually do that if the double-reading has unfortunate timing. It's also possible that this depends on the printer firmware and how often it reports temperature readings.

Unfortunately, this all looks rather more complicated than a quick fix is capable of. I'll have more of a think about it.

**Comment by AlexVerrico** [comment]
Looks like you're right, as it turns out I have been using the old logic in my installation.
I'm currently too busy with work to be able to provide much assistance with this, once work backs off a bit I'll plan to revisit this issue.
The logic may need to be scrapped completely and rewritten from scratch, which is not small feat.

**Comment by BobVul** [comment]
Thanks for confirming I'm not seeing things.

I've started a logic rewrite in PR #29, still untested. I'll try to do some testing over the next week.

Please let me know if you have any thoughts about my proposed new approach.

Of course, this is all hobby so only when you have time :)

**Comment by BobVul** [comment]
Hi @AlexVerrico, have you had any chance to take a look at #29? I've been running it for a couple months now and it all seems fine.

**Comment by AlexVerrico** [comment]
Hi @BobVul 
Apologies for the delay, it's been a crazy few months. 
Could you possibly remind me, was #29 a replacement for this PR, or were we going to merge this one first, and then #29?
Cheers, Alex.

**Comment by BobVul** [comment]
Ah, sorry, #29 is a replacement for this PR. I found it easier to tackle the problem from a different angle (time since last successful transition) rather than what's currently being done (count of unsuccessful transitions). If you're okay with the approach used in #29, #28 should be ignored.

**Comment by AlexVerrico** [comment]
No worries, in that case I'll close this and merge #29.

**Pull request closed without merging**
